/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VersionsRouteImport } from './routes/versions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as EvaluationRouteImport } from './routes/evaluation'
import { Route as IndexRouteImport } from './routes/index'

const VersionsRoute = VersionsRouteImport.update({
  id: '/versions',
  path: '/versions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationRoute = EvaluationRouteImport.update({
  id: '/evaluation',
  path: '/evaluation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/evaluation': typeof EvaluationRoute
  '/settings': typeof SettingsRoute
  '/versions': typeof VersionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/evaluation': typeof EvaluationRoute
  '/settings': typeof SettingsRoute
  '/versions': typeof VersionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/evaluation': typeof EvaluationRoute
  '/settings': typeof SettingsRoute
  '/versions': typeof VersionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/evaluation' | '/settings' | '/versions'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/evaluation' | '/settings' | '/versions'
  id: '__root__' | '/' | '/evaluation' | '/settings' | '/versions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EvaluationRoute: typeof EvaluationRoute
  SettingsRoute: typeof SettingsRoute
  VersionsRoute: typeof VersionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/versions': {
      id: '/versions'
      path: '/versions'
      fullPath: '/versions'
      preLoaderRoute: typeof VersionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation': {
      id: '/evaluation'
      path: '/evaluation'
      fullPath: '/evaluation'
      preLoaderRoute: typeof EvaluationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EvaluationRoute: EvaluationRoute,
  SettingsRoute: SettingsRoute,
  VersionsRoute: VersionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
